title: Isaac Renato Aburto Alonzo
logo: https://media.licdn.com/dms/image/C4E03AQGqiNo7J2pH8w/profile-displayphoto-shrink_800_800/0/1662750417687?e=1699488000&v=beta&t=0hzLionnIR2P4SLzf2b37j3X7FwndwfImO6sS0NNEL8
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
